[package]
name = "xmly-exporter"
version = "0.1.0"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"

[dependencies]
clipboard = "*"
conrod = { version = "*", features = ["glium", "winit"] }
image = "*"
lazy_static = "*"
rand = "*"
reqwest = "*"
serde_json = "*"
tempfile = "*"
